apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-clusterip
spec:
  selector:
    app: my-nginx
  type: NodePort
  ports:
  - port: 80  # Service端口  相当于用上面自定义的ip地址拼接这个端口号 就是访问service服务 然后转发到
    nodePort: 30002
    targetPort: 80 # pod端口  有标签值pod里面的80端口上
