version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - php
    networks:
      - lnmp_network

  php:
    image: php:8.0-fpm
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - lnmp_network

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lnmp_network

volumes:
  mysql_data:

networks:
  lnmp_network:
    driver: bridge

